language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g nw
  - npm install -g nw-builder@2.1.0
before_deploy:
  - nwbuild -v 0.12.3 -p win32,win64 .
  - cd build
  - zip -r so-console-win32.zip so-console/win32/*
  - zip -r so-console-win64.zip so-console/win64/*
deploy:
  provider: releases
  api_key: "$GITHUB_PUB_TOKEN"
  file:
    - "build/so-console-win32.zip"
    - "build/so-console-win64.zip"
  skip_cleanup: true
  on:
    tags: true